execution:
    uuid: cdd178da-da29-4af9-8dfb-234f1d90b364
    runtime:
        start: 2026-03-05T14:32:55.085846-07:00
        end: 2026-03-05T14:32:55.227266-07:00
        duration: 141420 microseconds
    execution_context:
        type: synchronous

action:
    type: method
    plugin: !ref 'environment:plugins:diversity-lib'
    action: shannon_entropy
    inputs:
    -   table: d216a709-86dd-4057-b412-b3de9b59a269
    parameters:
    -   drop_undefined_samples: false
    -   base: 2
    output-name: vector
    citations:
    - !cite 'action|diversity-lib:2026.1.0|method:shannon_entropy|0'

transformers:
    inputs:
        table:
        -   from: BIOMV210DirFmt
            to: biom.table:Table
            plugin: !ref 'environment:plugins:types'
            citations:
            - !cite 'view|types:2026.1.0|BIOMV210DirFmt|0'
            - !cite 'view|types:2026.1.0|biom.table:Table|0'
    output:
    -   from: pandas.core.series:Series
        to: AlphaDiversityDirectoryFormat
        plugin: !ref 'environment:plugins:types'
        citations:
        - !cite 'view|types:2026.1.0|pandas.core.series:Series|0'

environment:
    platform: Linux-4.18.0-553.92.1.el8_10.x86_64-x86_64-with-glibc2.28
    python: |-
        3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0]
    framework:
        version: 2026.1.0
        website: https://qiime2.org
        citations:
        - !cite 'framework|rachis:2026.1.0|0'
    plugins:
        types:
            version: 2026.1.0
            website: https://github.com/qiime2/q2-types
        diversity-lib:
            version: 2026.1.0
            website: https://github.com/qiime2/q2-diversity-lib
    python-packages:
        altair: 6.0.0
        annotated-types: 0.7.0
        anyio: 4.12.1
        appdirs: 1.4.4
        argcomplete: 3.6.3
        argon2-cffi: 25.1.0
        argon2-cffi-bindings: 25.1.0
        arrow: 1.4.0
        asttokens: 3.0.1
        atpublic: 7.0.0
        attrs: 25.4.0
        autocommand: 2.2.2
        backports.tarfile: 1.2.0
        bcrypt: 5.0.0
        beautifulsoup4: 4.14.3
        bibtexparser: 1.4.3
        biom-format: 2.1.16
        bleach: 6.3.0
        Brotli: 1.2.0
        brotlicffi: 1.2.0.0
        cached-property: 1.5.2
        certifi: 2026.1.4
        cffi: 2.0.0
        chardet: 5.2.0
        charset-normalizer: 3.4.4
        click: 8.1.8
        colorama: 0.4.6
        comm: 0.2.3
        conda-pack: 0.8.1
        contourpy: 1.3.2
        cryptography: 46.0.3
        cutadapt: '5.1'
        cycler: 0.12.1
        deblur: 1.1.1
        debugpy: 1.8.18
        decorator: 4.4.2
        defusedxml: 0.7.1
        DendroPy: 5.0.8
        dill: 0.4.1
        dnaio: 1.2.2
        dnspython: 2.8.0
        emperor: 1.0.5
        entrezpy: 2.1.3
        entrypoints: '0.4'
        exceptiongroup: 1.3.1
        executing: 2.2.1
        fastcluster: 1.3.0
        fastjsonschema: 2.21.2
        feedparser: 6.0.12
        filelock: 3.20.3
        flufl.lock: 9.0.0
        fonttools: 4.61.1
        formulaic: 1.2.1
        fqdn: 1.5.1
        frictionless: 5.5.0
        future: 1.0.0
        globus-sdk: 4.3.1
        h11: 0.16.0
        h2: 4.3.0
        h5py: 3.11.0
        hdmedians: 0.14.2
        hpack: 4.1.0
        httpcore: 1.0.9
        httpx: 0.28.1
        humanize: 4.15.0
        hyperframe: 6.1.0
        idna: '3.11'
        ijson: 3.4.0.post0
        importlib_metadata: 8.7.1
        inflate64: 1.0.4
        iniconfig: 2.3.0
        interface_meta: 1.3.0
        invoke: 2.2.1
        iow: 1.0.5
        ipykernel: 6.29.5
        ipython: 8.21.0
        ipython_genutils: 0.2.0
        ipywidgets: 8.1.8
        isal: 0.0.0
        isodate: 0.7.2
        isoduration: 20.11.0
        jaraco.context: 6.1.0
        jaraco.functools: 4.4.0
        jaraco.text: 4.0.0
        jedi: 0.19.2
        Jinja2: 3.1.6
        joblib: 1.5.3
        jsonpointer: 3.0.0
        jsonschema: 4.26.0
        jsonschema-specifications: 2025.9.1
        jupyter-events: 0.12.0
        jupyter_client: 7.4.9
        jupyter_core: 5.9.1
        jupyter_server: 2.17.0
        jupyter_server_terminals: 0.5.4
        jupyterlab_pygments: 0.3.0
        jupyterlab_widgets: 3.0.16
        kiwisolver: 1.4.9
        lark: 1.3.1
        llvmlite: 0.42.0
        lxml: 5.2.2
        lz4: 4.4.5
        markdown-it-py: 4.0.0
        marko: 2.2.2
        MarkupSafe: 3.0.3
        matplotlib: 3.8.4
        matplotlib-inline: 0.2.1
        mdurl: 0.1.2
        mistune: 3.2.0
        more-itertools: 10.8.0
        multivolumefile: 0.2.3
        munkres: 1.1.4
        mypy_extensions: 1.1.0
        narwhals: 2.15.0
        natsort: 8.4.0
        nbclassic: 1.3.3
        nbclient: 0.10.4
        nbconvert: 7.16.6
        nbformat: 5.10.4
        ncbi-datasets-pyclient: 18.4.0
        nest_asyncio: 1.6.0
        networkx: '3.1'
        nlopt: 2.9.0
        notebook: 6.5.5
        notebook_shim: 0.2.4
        numba: 0.59.1
        numpy: 1.26.4
        overrides: 7.7.0
        packaging: '25.0'
        pandas: 2.2.2
        pandera: 0.28.1
        pandocfilters: 1.5.0
        paramiko: 4.0.0
        parsl: 2024.4.15
        parso: 0.8.5
        PASTA: 1.9.3
        patsy: 0.5.6
        petl: 1.7.17
        pexpect: 4.9.0
        pickleshare: 0.7.5
        pillow: 10.3.0
        pip: '25.3'
        platformdirs: 4.4.0
        pluggy: 1.6.0
        ply: '3.11'
        prometheus_client: 0.24.1
        prompt_toolkit: 3.0.52
        psutil: 7.2.1
        ptyprocess: 0.7.0
        pure_eval: 0.2.3
        py7zr: 1.0.0
        pybcj: 1.0.7
        pycparser: '2.22'
        pycryptodomex: 3.23.0
        pydantic: 2.12.5
        pydantic_core: 2.41.5
        Pygments: 2.19.2
        pyhmmer: 0.12.0
        PyJWT: 2.10.1
        pymongo: 4.16.0
        PyNaCl: 1.5.0
        pynndescent: 0.5.13
        pyparsing: 3.3.2
        pyppmd: 1.1.0
        PyQt5: 5.15.9
        PyQt5-sip: 12.12.2
        PySocks: 1.7.1
        pytest: 9.0.2
        python-dateutil: 2.9.0.post0
        python-dotenv: 1.2.1
        python-json-logger: 2.0.7
        python-slugify: 8.0.4
        pytz: '2025.2'
        PyYAML: 6.0.3
        pyzmq: 24.0.1
        pyzotero: 1.8.0
        pyzstd: 0.16.2
        q2-alignment: 2026.1.0
        q2-boots: 2026.1.0
        q2-composition: 2026.1.0+0.g4b3aa86.dirty
        q2-cutadapt: 2026.1.0
        q2-dada2: 2026.1.0
        q2-deblur: 2026.1.0
        q2-demux: 2026.1.0
        q2-diversity: 2026.1.0
        q2-diversity-lib: 2026.1.0
        q2-emperor: 2026.1.0
        q2-feature-classifier: 2026.1.0
        q2-feature-table: 2026.1.0
        q2-fondue: 2026.1.0
        q2-fragment-insertion: 2026.1.0
        q2-kmerizer: 2026.1.0
        q2-longitudinal: 2026.1.0
        q2-metadata: 2026.1.0
        q2-mystery-stew: 2026.1.0
        q2-phylogeny: 2026.1.0
        q2-quality-control: 2026.1.0
        q2-quality-filter: 2026.1.0
        q2-sample-classifier: 2026.1.0
        q2-stats: 2026.1.0
        q2-taxa: 2026.1.0
        q2-types: 2026.1.0
        q2-vizard: 2026.1.0
        q2-vsearch: 2026.1.0
        q2cli: 2026.1.0
        q2galaxy: 2026.1.0
        q2templates: 2026.1.0
        qiime2: 2026.1.0
        rachis: 2026.1.0
        referencing: 0.37.0
        requests: 2.32.5
        rescript: 2026.1.0
        rfc3339_validator: 0.1.4
        rfc3986: 2.0.0
        rfc3986-validator: 0.1.1
        rfc3987-syntax: 1.1.0
        rich: 14.3.1
        rnanorm: 2.1.0
        rpds-py: 0.30.0
        rpy2: 3.5.11
        scikit-bio: 0.6.2
        scikit-learn: 1.4.2
        scipy: 1.13.0
        seaborn: 0.12.2
        Send2Trash: 2.1.0
        sepp: 4.5.5
        setproctitle: 1.3.7
        setuptools: 80.10.1
        sgmllib3k: 1.0.0
        shellingham: 1.5.4
        simpleeval: 1.0.3
        simplegeneric: 0.8.1
        sip: 6.7.12
        six: 1.17.0
        sniffio: 1.3.1
        soupsieve: 2.8.3
        stack_data: 0.6.3
        statsmodels: 0.14.5
        stringcase: 1.2.0
        tabulate: 0.9.0
        tblib: 3.2.2
        terminado: 0.18.1
        text-unidecode: '1.3'
        texttable: 1.7.0
        threadpoolctl: 3.6.0
        tinycss2: 1.5.1
        toml: 0.10.2
        tomli: 2.4.0
        tomlkit: 0.14.0
        tornado: 6.5.3
        tqdm: 4.67.1
        traitlets: 5.9.0
        typeguard: 4.4.4
        typer: 0.21.1
        typer-slim: 0.21.1
        typing-inspection: 0.4.2
        typing_extensions: 4.15.0
        typing_inspect: 0.9.0
        typing_utils: 0.1.0
        tzdata: '2025.3'
        tzlocal: '2.1'
        umap-learn: 0.5.7
        unicodedata2: 17.0.0
        unifrac: 1.3.0
        uri-template: 1.3.0
        urllib3: 2.5.0
        validators: 0.35.0
        wcwidth: 0.4.0
        webcolors: 25.10.0
        webencodings: 0.5.1
        websocket-client: 1.9.0
        wheel: 0.45.1
        whenever: 0.9.5
        widgetsnbextension: 4.0.15
        wrapt: 2.0.1
        xmltodict: 1.0.2
        xopen: 2.0.2
        yq: 3.4.3
        zipfile-deflate64: 0.0.0
        zipp: 3.23.0
        zlib-ng: 0.0.0
        zstandard: 0.23.0
